### ISSUE TITLE
 WITH_CUDA  Enable on VS 2013, Windows 10 64bit

### ISSUE THREAD

**Issue by Ahryman40k** [jlblancoc/suitesparse-metis-for-windows#17]
Same problem with VS 2013, Windows 10 64bit
Enabling WITH_CUDA option produces :
 "GPUQREngine.hpp" cannot be opened for compiling SPQR. 
 And some "unknown size" errors in t_cholmod_gpu.c

**Comment by Lokeshmsit** [comment]
i'm also getting same chain of errors with CUDA enabled.

**Comment by TzWeiz** [comment]
The GPUQREnginehpp cannot be opened can be solved by editing codes found near the bottom of the file SP_ROOT/SuiteSparse/CMakeLists.txt.
The edited version is as shown: 
![makefile changes](https://cloud.githubusercontent.com/assets/19992914/24743010/21bf4e48-1adf-11e7-8e05-11d5f2052643.JPG)
As illustracted in the picture, below are the changes:
1. by commenting or removing the line: CACHE STRING "list of all sub-directories to add to CMake build"  
2. reorder the code segment if(WITH_CUDA).... 
3. append ${SUBPROJECTS_TO_ADD} to the lower set
Then re-generate the code with CMake. 

The unknown size can be fixed by casting the void pointers. 
See https://social.msdn.microsoft.com/Forums/en-US/043c1583-cbf3-4402-93c2-efc55cd70892/error-c2036-void-unknown-size?forum=vcgeneral

For other problems after these fixes, I suggest looking at https://github.com/jlblancoc/suitesparse-metis-for-windows/issues/4
